version: '3.7'
services:
  my-server:
    image: rutkowski/cod2:2.5-server1.3-mysqlvoron-speex
    container_name: my-server
    user: "1001:1002"
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 28970:28970
      - 28970:28970/udp
    volumes:
      - ./my-server:/cod2/my-server
      - ~/cod2/main/1_3:/cod2/main:ro
      - ~/cod2/Library:/cod2/.callofduty2/my-server/Library:ro
    environment:
      PARAMS_BEFORE: "+exec server.cfg"
      COD2_SET_fs_homepath: "/cod2/.callofduty2/"
      COD2_SET_fs_game: "my-server"
      COD2_SET_dedicated: 2
      COD2_SET_net_port: 28970
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
