name: ci

on: push

jobs:
  build:
    strategy:
      matrix:
        cod2_patch: [3]
        mysql_variant: [2]
        speex: [0]
        enable_unsafe: [1]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build all images and push
        run: |
          PUSH_VALUE=1
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            PUSH_VALUE=1
          fi

          ./scripts/build.sh \
            --image_name=rutkowski/cod2 \
            --cod2_patch=${{ matrix.cod2_patch }} \
            --mysql_variant=${{ matrix.mysql_variant }} \
            --speex=${{ matrix.speex }} \
            --enable_unsafe=${{ matrix.enable_unsafe }} \
            --push=$PUSH_VALUE
