name: Build docker image

on: push

jobs:
  call-reusable-workflow:
    name: Build docker image
    uses: ./.github/workflows/build-push.yml
    with:
      cod2_patch: 3
      mysql_variant: 2
      enable_speex: 1
      enable_unsafe: 1
      enable_push: false
    secrets: inherit
