name: Periodic Docker Image Scan

on:
  schedule:
    - cron: '0 5 * * 0'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Environment
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read version file
        run: echo "VERSION=$(cat __version__)" >> $GITHUB_ENV

      - name: Construct Docker Image Tag
        run: |
          echo "DOCKER_IMAGE_TAG=rutkowski/cod2:${{ env.VERSION }}-server1.3-mysql-unsafe" >> $GITHUB_ENV
  
      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_IMAGE_TAG }}

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates
          curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy Vulnerability Scanner
        run: trivy image --severity HIGH,CRITICAL --exit-code 0 --no-progress ${{ secrets.DOCKER_IMAGE_TAG }} # CoD2 engine is obsolete, so getting only a few vulnerabilities isn't that bad
