name: Create release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Build and push docker image
    uses: ./.github/workflows/build-push.yml
    strategy:
      matrix:
        cod2_patch: [3]
        mysql_variant: [1, 2]
        enable_speex: [0, 1]
        enable_unsafe: [0, 1]
    with:
      cod2_patch: ${{ matrix.cod2_patch }}
      mysql_variant: ${{ matrix.mysql_variant }}
      enable_speex: ${{ matrix.enable_speex }}
      enable_unsafe: ${{ matrix.enable_unsafe }}
      enable_push: true
      libcod_commit: "5f04a7f4e60d910945f13a786d15081843b72baf"
    secrets: inherit
