name: Create release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Build and push docker image
    uses: ./.github/workflows/build-push.yml
    strategy:
      matrix:
        cod2_patch: [3]
        mysql_variant: [1, 2]
        enable_speex: [0, 1]
        enable_unsafe: [0, 1]
    with:
      cod2_patch: ${{ matrix.cod2_patch }}
      mysql_variant: ${{ matrix.mysql_variant }}
      enable_speex: ${{ matrix.enable_speex }}
      enable_unsafe: ${{ matrix.enable_unsafe }}
      enable_push: true
    secrets: inherit
  
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Read version file
        run: echo "VERSION=$(cat __version__)" >> $GITHUB_ENV

      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create and push tag
        run: |
          git tag -fa ${{ env.VERSION }} -m "Release ${{ env.VERSION }}"
          git push origin --tags --force

